### ISSUE TITLE
docker运行是否支持传递环境变量，如传递数据库主机IP，端口，用户名和密码

### ISSUE THREAD

**Issue by charnet1019** [Safe3/uuWAF#18]

**Comment by Safe3** [comment]
修改compose文件就可以，自行查一查文件格式

**Comment by charnet1019** [comment]
已实现，用到的文件如下，希望可以帮到有需要的人：
**Dockerfile:**
```
FROM centos:7

WORKDIR /uuwaf

COPY uuwaf .
COPY docker-entrypoint.sh .

RUN chmod +x /uuwaf/waf-service && \
    chmod +x /uuwaf/sbin/uuwaf && \
    chmod +x /uuwaf/captcha/captchaServer && \
    chmod +x /uuwaf/docker-entrypoint.sh

ENTRYPOINT ["/uuwaf/docker-entrypoint.sh"]
CMD ["/uuwaf/waf-service"]
```

**docker-entrypoint.sh:**
```bash
#!/bin/sh

set -e

WEB_CONF_BASE_DIR="/uuwaf/web/conf"
WEB_CONF_TMPL="${WEB_CONF_BASE_DIR}/conf_tmpl.yaml"
WEB_CONF="${WEB_CONF_BASE_DIR}/conf.yaml"



#render_web_conf_settings() {
#envsubst < ${WEB_CONF_TMPL} > ${WEB_CONF}
#}

render_web_conf_settings() {
cat << EOF > ${WEB_CONF}
addr: :4443
#dsn: root:Safe3.WAF@tcp(172.22.0.7:3306)/uuwaf?charset=utf8&parseTime=true&loc=Local
dsn: $DB_USERNAME:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT)/$DB_NAME?charset=utf8&parseTime=true&loc=Local
#jwtKey: G9uP5NvCmBHLU8ktAUetDx0b38g7fakL
jwtKey: $JWTKEY
expireTime: 43200
wafNodes:
 - 127.0.0.1:4444
EOF
}

gen_domain_ssl_cert() {
    if [ ! -f ${WEB_CONF_BASE_DIR}/.lock ]; then
        rm -f ${WEB_CONF_BASE_DIR}/*.crt
        rm -f ${WEB_CONF_BASE_DIR}/*.key

        /uuwaf/waf-service -c "${DOMAIN_NAME}"
        touch ${WEB_CONF_BASE_DIR}/.lock
    fi
}


_main () {
    render_web_conf_settings
    gen_domain_ssl_cert
 
    exec "$@"
}


######### entrypoint
_main "$@"
```

**k8s编排:**
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uuwaf-data
  namespace: waf
spec:
  #storageClassName: nfs-based-cstor-storage
  storageClassName: openebs-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uuwaf
    component: secure
  name: uuwaf
  namespace: waf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: uuwaf
      component: secure
  template:
    metadata:
      labels:
        app: uuwaf
        component: secure
    spec:
      imagePullSecrets:
      - name: harborsecret
      volumes:
      - name: uuwaf-data
        persistentVolumeClaim:
          claimName: uuwaf-data
      containers:
      - name: uuwaf
        image: uuwaf:2.5.1
        volumeMounts:
        - name: uuwaf-data
          mountPath: /uuwaf/web/conf
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: mysql-headless.middleware
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          value: uuwaf
        - name: DB_PASSWORD
          value: uLxxxxxxxxxxx
        - name: DB_NAME
          value: uuwaf
        - name: JWTKEY
          value: P8uxxxxxxxxxxxxxxxxxxx
        - name: DOMAIN_NAME
          value: 192.168.5.3
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: web-admin
          containerPort: 4443
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: uuwaf
    component: secure
  name: uuwaf
  namespace: waf
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: web-admin
    port: 4443
    protocol: TCP
    targetPort: 4443
  selector:
    app: uuwaf
    component: secure
  type: ClusterIP
```
