### ISSUE TITLE
有没有纯净版的docker-compose安装文件，不想使用一键安装

### ISSUE THREAD

**Issue by leim** [Safe3/uuWAF#40]
**Is your feature request related to a problem? Please describe.**
一键安装脚本，既安装程序又安装数据库，我们本身有现成的数据库，直接使用即可，不需要这个一键安装自带的

**Describe the solution you'd like**
完全手工配置的安装方式

**Describe alternatives you've considered**

**Additional context**

**Comment by Safe3** [comment]
你可以参考一键安装脚本来手工安装

**Comment by hilyary** [comment]
你改一下docker-compose.yml不就可以了吗

**Comment by 21307369** [comment]
docker-compose.yml
第一次先把  取消挂载文件 把文件复制到主机然后在挂载进去
``` yml
services:
    uuwaf:
        command:
            - /run.sh
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            - TZ=Asia/Shanghai
        image: uusec/nanqiang:latest
        network_mode: host
        ulimits:
            nofile:
                hard: 102400
                soft: 102400
            nproc: 65535
        volumes:
            - ./data/server.key:/uuwaf/web/conf/server.key
            - ./data/server.crt:/uuwaf/web/conf/server.crt
            - ./data/error.log:/uuwaf/logs/error.log          
            - ./data/plugins/ip-intelligence.lua:/uuwaf/waf/plugins/ip-intelligence.w
            - ./data/uuwaf.conf:/uuwaf/conf/uuwaf.conf
            - ./data/conf.yaml:/uuwaf/web/conf/conf.yaml
```
